imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

# Assetic Configuration
assetic:
    filters:
        yui_css:
            apply_to: "\.css$"
            jar: %kernel.root_dir%/../vendor/nervo/yuicompressor.jar
        yui_js:
            apply_to: "\.js$"
            jar: %kernel.root_dir%/../vendor/nervo/yuicompressor.jar

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
